- ada/ada
Hi Onno,
VOMS tools use default path to /tmp/x509up_u${UID}. ada should use that, too.
> use default path to proxy if $X509_USER_PROXY is not set

- ada/ada
If $X509_CERT_DIR is set, it shall be used as capath. Otherwise fall back to default /etc/grid-security/certificates
> use $X509_CERT_DIR as capath if it is set

- ada/ada
In case no authentication method is specified in commandline (--tokenfile, --netrc, --proxy), the environmentable variable BEARER_TOKEN is used if it exists. 
To test:
`export BEARER_TOKEN=...`
`ada --whoami --api https://dcachetest.grid.surfsara.nl:20443/api/v1`
> Bearer token variable

- ada/ada
TODO: Capture this error: 403 Error: Forbidden
> Bulk staging

- ada/ada
Fixes to bulk staging:
- Stage file-list as array in a single bulk request
- Put target in requests.log
- Add activity (PIN ur UNPIN) of bulk request in requests.log
- Except for storing the request ID in ~/.ada/requests.log, return the request ID to the prompt when a stage/unstage command is submitted.
- In debug mode, mention that information about bulk request is logged in requests.log
- Remove default lifetime from unstage/unpin command
> Fixes in bulk staging function

- ada/ada
The `--version` option relies on `git describe` command to determine the software version. This requires the script to be located within a valid git repository, which may not always be the case.
This patch tries to determine the software version using git and adds a fallback value (`unknown`) in case this is not possible.
Using the variable `_VERSION_PLACEHOLDER` allows third party tools such as Ansible to edit this specific line with the proper version at the time of deployment.
> Define fallback value for --version option

- ada/ada
Fixes https://github.com/sara-nl/SpiderScripts/issues/15
> Implement --setlabel and --rmlabel

- ada/ada
The --whoami command will now include the API it is talking to, and the version(s) of dCache. This might be helpful for debugging.
> With --whoami, include info about dCache

- ada/ada
The option --igtf requires 'true' or 'false' as a value. If the option is not specified, 'true' is assumed. Most dCache APIs have IGTF compatible host certificates (also called: Grid certificates), which require the curl option `--capath`, to point curl to the Grid root CA certificates. But when a dCache API does not have a Grid certificated, but instead a "normal" certificate like a "Let's Encrypt" cert, the curl option `--capath` should not be used. So, in such a case, you can use `--igtf false`, or in the ada.conf `igtf=false`, to prevent the curl option `--capath`. Curl then uses its own set of root CA certificates.
If Ada just works for you, you don't need this option. If Ada has trouble connecting to an API, try this option.
Also, don't print the entire manual when an invalid option …
> Ada: add option --igtf. Fixes #10.

- ada/ada
- ada/etc/ada.conf
Tell Ada to look for an ada.conf in the same dir as where the script is (last in order of preference after /etc/ada.conf and ~/.ada/ada.conf).
Not that $debug is always false when ada.conf is sourced, because the env variables and commandline arguments are set later. So I removed the line:
```
$debug && echo "Loading $configfile"
```
> Use ada/etc/ada.conf if it exists 

- ada/ada
* Fail when token will expire in 10 seconds
* Fail when token will expire in 60 seconds, when `--recursive` was specified
* Fix `date` command for MacOS; added -u to assume UTC instead of local time
* Don't validate token when command is `--viewtoken`, because we want to view tokens that are invalid.
* Fix: `tr: Illegal byte sequence`
> Fail early when token is about to expire

- ada/ada
* Linux doesn't understand `-mtime +10h`
* Used -amin (access) instead of -mmin (modification) because then we won't delete files that are actively used
> Fix find command for Linux; use access time instead of modification time

- ada/ada
* Ada config files should not be world writable
* Tokenfiles should be neither world readable nor world writable
> Check file permissions before loading them

- tests/integration_test.sh
After token is created, this need to be loaded for all integration tests to succeed.
> Fix failure running intergration test when tokenfile is newly created

- ada/ada
- tests/integration_test.sh
If channelname is already used, --resume needs to be added to resume
If channelname is not stored locally, --force also needs to be added to resume
> Check unique channel name

- ada/ada
With `ada --checksum` and `ada --stat`, the API's `/id` call is used; mainly for historical reasons. But the `/id` API call will soon be changed. Anyway, we don't need it anymore, because we can now get the same info with the `/namespace` call, which even saves one API operation per file. 
This change replaces Ada's `/id` calls with `/namespace` calls. The output of `ada --checksum` is still the same. The output of `ada --stat` will probably be a bit different.
> Replace /id api call with /namespace

- ada/ada
Mainly double quoting variables to prevent shell globbing
> Some minor code improvements based on Shellcheck

- ada/ada
Fixes two issues:
* The integration test fails the first time and succeeds the second time
* Sometimes, channel files in .ada/channels/ don't have the channel ID in their name
> Fix #96: sometimes channel gets lost

- ada/ada
The local files `channel-name-${channel_id}` and `channel-status-${channel_id}` should be cleaned up after the channel is deleted.
> Delete local channelfiles after deleting channel

- ada/ada
- tests/unit_test.sh
Improved validation for --events and --report-staged
Fixes #102
I cherry-picked two commits from branch https://github.com/sara-nl/SpiderScripts/pull/106
> 102 do not create channel if folder does not exist

- ada/ada
Example (file named "6" is being written):
```
[onno@mylaptop ~/git/SpiderScripts] % ada/ada --api https://dcacheview.grid.surfsara.nl:22880/api/v1 --longlist /pnfs/grid.sara.nl/data/users/onno/tape/test2/
5  14  2025-09-03 14:05 UTC  tape  ONLINE_AND_NEARLINE
6  -   2025-09-03 14:07 UTC  tape  NONE
```
Fixes #109
> If size is empty (because upload not finished), show dash

- ada/ada
> Catch 403 with (un)stage and explain possible causes

- ada/ada
Symlinks always have permissions `rwxrwxrwx`. It's the file they point to that we want to check, not the link itself. This is done via `realpath`.
Fixes #127
> Use realpath for permissions check, to test real files and not symlinks
